language: python
dist: xenial
sudo: false
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5-dev
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6-dev
    env: TOXENV=py36
  - name: Python 3.7 on Xenial Linux
    python: 3.7
    env: TOXENV=py37
    dist: xenial
    sudo: true
  - python: 3.8
    env: TOXENV=py38
  - python: 3.9
    env: TOXENV=py39
  - python: 3.9-dev
    env: TOXENV=py39
  - python: pypy2.7-6.0
    env: TOXENV=py35
  - python: pypy3.6-7.3.1
    env: TOXENV=ALL
notifications:
  email:
    recipients:
    - jtonye@ymail.com
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=django_extra_field_validation.settings
  global:
  - secure: lUKOMTqDQSvRriSOSXOuUAqCT6Gw13UVeaP//Tfp9gqnAcIb4OW9TlJv6/bELGMAGGbXeYEjIPJOXUrsqxUaIRpjua99t3iJj6evTazs8GBDd9DSmPb/UOd2wshsRg/kqVanJ6v2zRl+kmCLerniRjvJunjQAC9HGYE11iJdvq7YPvoXjjEN15ZbrLndk7b1ghyBHLatgqVGRrCBw6+I3HJaIzCcXHHF/UOVOrUQ+KkfGrmxFKFR6UeM/mw/MWvKIbLI0rrpMv9LcyfX+odclu4tnEWfvc819dxaUuL5wSbsMAlOA/xnY6nPvxw6cqTV0teKnPj4HrFjHuJa2cvNn1JB4zUSBeP+EdiyAV+ItKCVpWP8i4h79aYcYH0JyA4Npnlug9/HKG21QJnS06DAU/rJOmBtbeTiDj1RqPUwP8boKhD0mQ67uUuIHlkBlkQE/DGrwxSVnCnSGAmZ4l/hp6t0Hbh5k1Sq+aFvJwTcnVLIsoGptmlHvgxuudLSN/CUWlIMLTN1KLxdv0RpxSJiZHOYw+nJFn0xNIMWDxcTxy58RznDmr3LLV1wK4hN1yyqdyN533Su/xVvz9OAWwszWvY1oI82yRKpNqLFyyFiA2LbRT8mHxOVauSeWAjpP/fmMLlACiYFv+4PO2AcX/9ujypAGpCPgf0sd55jkpDybgI=
install:
- pip install -U pip tox
script:
- sqlite3 --version
- tox
